name: NASA Project CI
on:
  push:
    branches : [master]
  pull_request:
    branches: [master]
jobs:
  build:
    env:
      CI: true
      MONGODB: mongodb://localhost/ztm
    strategy:
      matrix: 
        node-version: [16.x]
        mongodb-version: ['4.4']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{matrix.mongodb-version}}
      - run : npm install
      - run : npm run build --prefix client
      - run : npm test